name: CI build

on:
  schedule:
  - cron:  '12 6 * * *'
  #~ push:
    #~ branches:
      #~ - master
    #~ paths-ignore:
      #~ - 'data.chennai.csv'
  

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: ubuntu-18.04
    #~ strategy:
      #~ fail-fast: false
      #~ max-parallel: 6
      #~ matrix:
        #~ python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        #~ python-version: ${{ matrix.python-version }}
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install -y poppler-utils phantomjs gnumeric
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1    
    - name: Scrape city beds data
      run: |
        python scraper.py
    - name: Commit modified csv files
      if: always()
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "Automated report"
        git push
